version: "3"

services:
  apisix:
    image: apache/apisix:3.1.0-debian
    ports:
      - "9080:9080"
      - "9180:9180"
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
  etcd:
    image: bitnami/etcd:3.5.7
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"
  server:
    build: .